name: 'qsbot-slack-messenger'
description: 'Send messages to slack webhooks'
inputs:
  slackToken:
    description: 'Slack token'
    required: true
  baseUrl:
    description: 'Base slack url'
    required: true
  conversationsListPath:
    description: 'Url path to use for conversations.list api'
    required: true
  postMessagePath:
    description: 'Url path to use for chat.postMessage api'
    required: true
  channelName:
    description: 'Name of slack channel'
    required: true
  message:
    description: 'Message to send'
    required: true
    default: 'Hello from GitHub Actions'
outputs:
  response:
    description: 'Response from slack'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'green'
