name: ci-workflow
run-name: General Ci Actions

on:
  push:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: NPM Install
        run: npm ci

      - name: Lint
        id: linting
        run: npx eslint -c .eslintrc.js .
        continue-on-error: true

      - if: ${{ steps.linting.outcome == 'failure' }}
        name: Send Status to Slack
        uses: Darth-Par/slackQSBot@v1.0.33
        id: slackMessaging
        with:
          slackToken: ${{ secrets.SLACK_TOKEN }}
          baseUrl: ${{ vars.BASE_URL }}
          conversationsListPath: ${{ vars.CONVERSATIONS_LIST_PATH }}
          postMessagePath: ${{ vars.POST_MESSAGE_PATH }}
          channelName: ${{ vars.CHANNEL_NAME }}
          message: 'Linting Status -> ${{ steps.linting.outcome }}'

      - if: ${{ steps.linting.outcome == 'failure'}}
        name: Error
        run: exit 1

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install typescript
        run: npm install -g typescript

      - name: Install NCC
        run: npm install -g @vercel/ncc

      - name: NPM Install
        run: npm ci

      - name: Build
        id: build
        run: npm run vBuild
        continue-on-error: true

      - if: ${{ steps.build.outcome == 'failure'}}
        name: Send Status to Slack
        uses: Darth-Par/slackQSBot@v1.0.33
        id: slackMessaging
        with:
          slackToken: ${{ secrets.SLACK_TOKEN }}
          baseUrl: ${{ vars.BASE_URL }}
          conversationsListPath: ${{ vars.CONVERSATIONS_LIST_PATH }}
          postMessagePath: ${{ vars.POST_MESSAGE_PATH }}
          channelName: ${{ vars.CHANNEL_NAME }}
          message: 'Build Status -> ${{ steps.linting.outcome }}'

      - if: ${{ steps.build.outcome == 'failure'}}
        name: Error
        run: exit 1

  send_pipeline_state:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    needs:
      - lint
      - build

    steps:
      - name: Send Pipeline Status To Slack
        uses: Darth-Par/slackQSBot@v1.0.33
        with:
          slackToken: ${{ secrets.SLACK_TOKEN }}
          baseUrl: ${{ vars.BASE_URL }}
          conversationsListPath: ${{ vars.CONVERSATIONS_LIST_PATH }}
          postMessagePath: ${{ vars.POST_MESSAGE_PATH }}
          channelName: ${{ vars.CHANNEL_NAME }}
          message: 'Custom GitHub Action Pipeline Status -> SUCCESS'
