name: general-ci-workflow
run-name: General Ci Actions
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - run: npm ci
      - run: npx eslint -c .eslint.js .
  build: 
    runs-on: ubuntu-latest
    steps:
      runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - run: npm install -g typescript
      - run: npm run vBuild
